name: Pylint

on:
  - push

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Analysing the code with pylint
        run: |
          uv run pylint $(git ls-files '*.py')
